### ISSUE TITLE
[BUG] Crash with MG mk.2

### ISSUE THREAD

**Issue by Carvercarver1** [Team-Immersive-Intelligence/ImmersiveIntelligence#231]
```
[20:17:14] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at pl.pabilo8.immersiveintelligence.common.entity.bullet.EntityBullet.<init>(EntityBullet.java:121) ~[EntityBullet.class:?]
	at pl.pabilo8.immersiveintelligence.api.bullets.AmmoUtils.createBullet(AmmoUtils.java:36) ~[AmmoUtils.class:?]
	at pl.pabilo8.immersiveintelligence.common.entity.EntityMachinegun.shootFromStack(EntityMachinegun.java:758) ~[EntityMachinegun.class:?]
	at pl.pabilo8.immersiveintelligence.common.entity.EntityMachinegun.shoot(EntityMachinegun.java:870) ~[EntityMachinegun.class:?]
	at pl.pabilo8.immersiveintelligence.common.entity.EntityMachinegun.onEntityUpdate(EntityMachinegun.java:290) ~[EntityMachinegun.class:?]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:389) ~[vg.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1958) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1762) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by Pabilo8** [comment]
Karvar supervised the fixing, (pls help, I'm now stored in a facility in Eastern Ukraine).
