### ISSUE TITLE
Mod cannot run on the server.

### ISSUE THREAD

**Issue by HazelnutCat** [Team-Immersive-Intelligence/ImmersiveIntelligence#268]
Mod cannot run on the Forge-1.12.2-14.23.5.2860 server. 
Here is the report.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  IILoadingPlugin (immersiveintelligence-core-0.3.0.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 23-10-4 12:37 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Intelligence (immersiveintelligence)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
	at pl.pabilo8.immersiveintelligence.common.util.IILib.<clinit>(IILib.java:82)
	at pl.pabilo8.immersiveintelligence.common.item.ammo.ItemIIBulletMagazine.<init>(ItemIIBulletMagazine.java:41)
	at pl.pabilo8.immersiveintelligence.common.IIContent.<clinit>(IIContent.java:155)
	at pl.pabilo8.immersiveintelligence.common.CommonProxy.preInit(CommonProxy.java:508)
	at pl.pabilo8.immersiveintelligence.ImmersiveIntelligence.preInit(ImmersiveIntelligence.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.ISound
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 41 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_371, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7944843464 bytes (7576 MB) / 8232370176 bytes (7851 MB) up to 8232370176 bytes (7851 MB)
	JVM Flags: 2 total; -Xmx8G -Xms8G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version      | Source                                  | Signature                                |
	|:----- |:--------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft             | 1.12.2       | minecraft.jar                           | None                                     |
	| LCH   | mcp                   | 9.42         | minecraft.jar                           | None                                     |
	| LCH   | FML                   | 8.0.99.99    | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                 | 14.23.5.2860 | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | immersiveengineering  | 0.12-98      | ImmersiveEngineering-0.12-98.jar        | None                                     |
	| LCE   | immersiveintelligence | 0.3.0        | immersiveintelligence-0.3.0.jar         | 770570c49a2652e64a9b29b9b9d9919ca68b7065 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
IILoadingPlugin (immersiveintelligence-core-0.3.0.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Pabilo8** [comment]
Fized by c9efc12bd2b52315fdb1adcbab08fd8e10272259
